apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JakubSocha2-TomTom/argo-tests.git
    targetRevision: HEAD
    path: argo/sample-app/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: orbis-light

  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true